web:
  build: .
  command: php -S 0.0.0.0:8080 -t /wordpress
  ports:
    - "8080:8080"
  links:
    - db
  volumes:
    - .:/wordpress
db:
  image: partlab/ubuntu-mariadb
  environment:
    MARIADB_DATABASE: wordpress

